import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './AddRector.css';
const API_URL=import.meta.env.VITE_API_URL||'http://localhost:5000';
const photoUrl=p=>{if(!p)return '';const v=String(p).trim();if(v.startsWith('http')||v.startsWith('data:'))return v;return `${API_URL}/uploads/admins/${v.replace(/^\/+/, '')}`};
export default function AddRector(){const navigate=useNavigate();const[admin,setAdmin]=useState(null);const[mobileMenuOpen,setMobileMenuOpen]=useState(false);const[form,setForm]=useState({rector_id:'',name:'',email:'',mobile:'',password:'',role:'Rector',status:'active',salary:''});const[file,setFile]=useState(null);const[error,setError]=useState('');useEffect(()=>{const t=localStorage.getItem('adminToken');if(!t){navigate('/admin/login',{replace:true});return}const s=localStorage.getItem('admin');if(s)try{setAdmin(JSON.parse(s))}catch{}},[navigate]);const close=()=>setMobileMenuOpen(false);const logout=()=>{localStorage.removeItem('adminToken');localStorage.removeItem('admin');navigate('/admin/login',{replace:true})};const nav=p=>{close();navigate(p)};const submit=async e=>{e.preventDefault();try{const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,v));if(file)fd.append('photo',file);const r=await fetch(`${API_URL}/api/admin/rectors`,{method:'POST',headers:{Authorization:`Bearer ${localStorage.getItem('adminToken')}`},body:fd});const d=await r.json();if(!r.ok||!d.success)throw Error(d.message||'Failed');navigate('/admin/rectors')}catch(e){setError(e.message)}};return <div className="rector-page"><Sidebar active="rector" admin={admin} nav={nav} logout={logout} open={mobileMenuOpen}/>{mobileMenuOpen&&<div className="rector-overlay" onClick={close}/>}<main><MobileHeader admin={admin} open={()=>setMobileMenuOpen(true)} profile={()=>navigate('/admin/profile')}/><Header title="Add Rector" subtitle="Create a new rector account." admin={admin} profile={()=>navigate('/admin/profile')}/><section className="rector-card"><form onSubmit={submit}><div className="rector-form-grid">{[['rector_id','Rector ID'],['name','Full Name'],['email','Email'],['mobile','Mobile'],['password','Password'],['role','Role'],['salary','Monthly Salary']].map(([k,l])=><label key={k}>{l}<input name={k} type={k==='password'?'password':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required={k!=='mobile'}/></label>)}<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="full">Photo<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div>{error&&<div className="rector-error">{error}</div>}<div className="rector-actions"><button type="button" onClick={()=>navigate('/admin/rectors')}>Cancel</button><button type="submit">Add Rector</button></div></form></section></main></div>}
function Header({title,subtitle,admin,profile}){return <header className="rector-header"><div><span>RECTOR MANAGEMENT</span><h1>{title}</h1><p>{subtitle}</p></div><button className="rector-top-profile" onClick={profile}>{admin?.photo?<img src={photoUrl(admin.photo)}/>: '👤'}</button></header>}
function MobileHeader({admin,open,profile}){return <div className="rector-mobile-header"><button onClick={open}>☰</button><strong>Rector Management</strong><button onClick={profile}>{admin?.photo?<img src={photoUrl(admin.photo)}/>: '👤'}</button></div>}
function Sidebar({active,nav,logout,open}){return <aside className={`rector-page-sidebar ${open?'mobile-open':''}`}><div className="rector-page-brand"><div className="rector-brand-icon">🏠</div><div><strong>Hostel</strong><span>Admin Panel</span></div></div><nav>{[['dashboard','📊 Dashboard','/admin/dashboard'],['students','🎓 Students','/admin/students'],['rooms','🛏️ Rooms','/admin/rooms'],['fees','💳 Fees','/admin/fees'],['complaints','📝 Complaints','/admin/complaints'],['cricket','🏏 Cricket Box','/admin/cricket-box'],['ann','📢 Announcements','/admin/announcements'],['reports','📊 Reports','/admin/reports'],['rector','👨‍💼 Rector Management','/admin/rectors'],['staff','👨‍💼 Staff Management','/admin/staff'],['profile','👤 Profile','/admin/profile']].map(([k,t,p])=><button key={k} className={active===k?'active':''} onClick={()=>nav(p)}>{t}</button>)}</nav><button className="rector-page-logout" onClick={logout}>🚪 Logout</button></aside>}
