import React,{useEffect,useRef,useState}from"react";
import{useNavigate}from"react-router-dom";
import{Html5Qrcode}from"html5-qrcode";
import"./StaffCricketQRScanner.css";
const API_URL=import.meta.env.VITE_API_URL||"http://localhost:5000";
const staff=()=>{try{return JSON.parse(localStorage.getItem("staff")||"{}")}catch{return{}}};
const photo=p=>{if(!p)return"";p=String(p).trim();if(/^data:|^blob:|^https?:/.test(p))return p;p=p.replace(/^\/+/, "");return p.startsWith("uploads/")?`${API_URL}/${p}`:`${API_URL}/uploads/staff/${p}`};
export default function StaffCricketQRScanner(){
 const nav=useNavigate(),scanner=useRef(null),busy=useRef(false),[open,setOpen]=useState(false),[result,setResult]=useState(null),[error,setError]=useState(""),[ready,setReady]=useState(false);
 const token=localStorage.getItem("staffToken"),s=staff(),p=photo(s.photo||s.profile_photo||s.staff_photo||localStorage.getItem("staffPhoto"));
 useEffect(()=>{if(!token){nav("/staff/login",{replace:true});return}start();return()=>stop()},[]);
 const start=async()=>{try{const q=new Html5Qrcode("sc-qr-reader");scanner.current=q;await q.start({facingMode:"environment"},{fps:10,qrbox:{width:250,height:250}},t=>{if(!busy.current){busy.current=true;verify(t)}},()=>{});setReady(true)}catch(e){setError("Unable to start camera. Please allow camera permission and try again.")}};
 const stop=async()=>{try{if(scanner.current?.isScanning)await scanner.current.stop();await scanner.current?.clear()}catch{}scanner.current=null};
 const verify=async(qr_token)=>{try{setError("");setResult(null);const r=await fetch(`${API_URL}/api/staff/cricket-box/scan`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({qr_token})});const d=await r.json();setResult(d);if(!r.ok)setError(d.message||"QR verification failed.")}catch(e){setError(e.message||"Unable to verify QR.")}finally{setTimeout(()=>busy.current=false,1200)}};
 const logout=()=>{["staffToken","staff","staffPhoto"].forEach(k=>localStorage.removeItem(k));nav("/staff/login")},go=x=>{setOpen(false);nav(x)};
 return <div className="sq-page">{open&&<div className="sq-overlay" onClick={()=>setOpen(false)}/>}<aside className={`sq-side ${open?"open":""}`}><div className="sq-brand">🏠 <span><strong>Hostel</strong><small>Staff Panel</small></span></div><nav><button onClick={()=>go("/staff/cricket-box")}>📊 Dashboard</button><button className="active" onClick={()=>go("/staff/cricket-box/scan")}>📷 Scan QR</button><button onClick={()=>go("/staff/cricket-box/history")}>📋 Scan History</button><button onClick={()=>go("/staff/profile")}>👤 My Profile</button></nav><button className="sq-logout" onClick={logout}>🚪 Logout</button></aside>
 <main className="sq-main"><header className="sq-top"><button className="sq-menu" onClick={()=>setOpen(true)}>☰</button><div><h1>Hostel Staff Panel</h1><span>Cricket Box QR Handler</span></div><div className="sq-photo">{p?<img src={p} alt="Staff"/>:"👤"}</div></header><section className="sq-content"><span>CRICKET BOX</span><h2>Scan Booking QR</h2><p>Scan the student's QR code to verify cricket box entry.</p><div className="sq-grid"><div className="sq-card"><div id="sc-qr-reader"/>{!ready&&!error&&<p className="sq-loading">Starting camera...</p>}{error&&<div className="sq-error">{error}</div>}<small>Keep the QR code inside the frame.</small></div><div className="sq-card"><h3>Verification Result</h3>{!result?<div className="sq-empty">📷<p>{error?"Scan again after fixing the issue.":"Scan a QR code to verify the booking."}</p></div>:<div className={`sq-result ${result.success?"valid":"invalid"}`}><b>{result.success?"✓":"✕"}</b><h4>{result.success?"ENTRY ALLOWED":"ENTRY DENIED"}</h4><p>{result.message}</p>{result.booking&&<div className="sq-summary">{[["Student",result.booking.student_name],["Ground",result.booking.ground_name],["Date",result.booking.booking_date],["Time",`${result.booking.start_time?.slice(0,5)} - ${result.booking.end_time?.slice(0,5)}`],["Payment",result.booking.payment_status]].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]||"-"}</strong></div>)}</div>}<button onClick={()=>{setResult(null);setError("")}}>Scan Another QR</button></div>}</div></div></section></main></div>
}