import React,{useEffect,useState}from"react";
import{useNavigate}from"react-router-dom";
import"./StaffCricketScanHistory.css";
const API_URL=import.meta.env.VITE_API_URL||"http://localhost:5000";
const getS=()=>{try{return JSON.parse(localStorage.getItem("staff")||"{}")}catch{return{}}};
const photo=p=>{if(!p)return"";p=String(p).trim();if(/^data:|^blob:|^https?:/.test(p))return p;p=p.replace(/^\/+/, "");return p.startsWith("uploads/")?`${API_URL}/${p}`:`${API_URL}/uploads/staff/${p}`};
export default function StaffCricketScanHistory(){const nav=useNavigate(),[open,setOpen]=useState(false),[logs,setLogs]=useState([]),[status,setStatus]=useState("All"),[error,setError]=useState(""),token=localStorage.getItem("staffToken"),s=getS(),p=photo(s.photo||s.profile_photo||s.staff_photo||localStorage.getItem("staffPhoto"));
useEffect(()=>{if(!token){nav("/staff/login",{replace:true});return}load()},[status]);
const load=async()=>{try{setError("");const q=status==="All"?"":`?status=${encodeURIComponent(status)}`,r=await fetch(`${API_URL}/api/staff/cricket-box/history${q}`,{headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok)throw Error(d.message);setLogs(d.logs||[])}catch(e){setError(e.message||"Unable to load history.")}};
const go=x=>{setOpen(false);nav(x)},logout=()=>{["staffToken","staff","staffPhoto"].forEach(k=>localStorage.removeItem(k));nav("/staff/login")};
return <div className="sh-page">{open&&<div className="sh-overlay" onClick={()=>setOpen(false)}/>}<aside className={`sh-side ${open?"open":""}`}><div className="sh-brand">🏠 <span><strong>Hostel</strong><small>Staff Panel</small></span></div><nav><button onClick={()=>go("/staff/cricket-box")}>📊 Dashboard</button><button onClick={()=>go("/staff/cricket-box/scan")}>📷 Scan QR</button><button className="active" onClick={()=>go("/staff/cricket-box/history")}>📋 Scan History</button><button onClick={()=>go("/staff/profile")}>👤 My Profile</button></nav><button className="sh-logout" onClick={logout}>🚪 Logout</button></aside><main className="sh-main"><header className="sh-top"><button className="sh-menu" onClick={()=>setOpen(true)}>☰</button><div><h1>Hostel Staff Panel</h1><span>Cricket Box QR Handler</span></div><div className="sh-photo">{p?<img src={p} alt="Staff"/>:"👤"}</div></header><section className="sh-content"><span>CRICKET BOX</span><h2>Scan History</h2><p>Review QR verification activity handled by the CricketBox QR Handler.</p>{error&&<div className="sh-error">{error}</div>}<div className="sh-filters">{["All","Valid","Expired","Invalid","Already Used","Rejected"].map(x=><button className={status===x?"active":""} onClick={()=>setStatus(x)} key={x}>{x}</button>)}</div><div className="sh-table"><table><thead><tr><th>Time</th><th>Student</th><th>Ground</th><th>Booking</th><th>Status</th><th>Remarks</th></tr></thead><tbody>{logs.length===0?<tr><td colSpan="6" className="empty">No scan records found.</td></tr>:logs.map(l=><tr key={l.id}><td>{new Date(l.scanned_at).toLocaleString("en-IN")}</td><td>{l.student_name||"-"}</td><td>{l.ground_name||"-"}</td><td>#{l.booking_id||"-"}</td><td><b className={`status ${String(l.scan_status).toLowerCase().replace(/\s+/g,"-")}`}>{l.scan_status}</b></td><td>{l.remarks||"-"}</td></tr>)}</tbody></table></div></section></main></div>}